### ISSUE TITLE
Connecting account to Discord shows error, but indicates it was successful

### ISSUE THREAD

**Issue by bouwe77** [kentcdodds/kentcdodds.com#136]
Steps to reproduce:
* Create account on kent.dev
* Log in via magic link
* Connect Discord account
* Authenticate with QR Code
* An error is displayed in the right bottom corner
* Which is quickly replaced by the "👋 Welcome to kent.dev. " message.
* The profile page indicates the Discord account is connected successfully.

I did not catch the exact error. I will try with one of my other accounts.

**Comment by bouwe77** [comment]
I first saw the error with my bouwe@bouwe.nl account, and when I tried with my testing account bob.atsma@gmail.com I saw it again:

![ScreenFlow](https://user-images.githubusercontent.com/4126793/135731633-ef40a7b6-b5cf-4950-8f28-7435e06f945c.gif)

The Network tab did not reveal anything.

**Comment by bouwe77** [comment]
Don't know if this is related, because it looks different, but:

Tried with my new account bouwe@bouwe.nl on the new live site (WHOOOOHOOO 🎉 ) and got an error on the Discord page URL:

https://discord.com/oauth2/authorize?client_id=738096608440483870&redirect_uri=https%3A%2F%2Fkentcdodds.com%2Fdiscord%2Fcallback&response_type=code&scope=identify+guilds.join+email+guilds

<img width="474" alt="Screenshot 2021-10-04 at 21 02 31" src="https://user-images.githubusercontent.com/4126793/135909337-7847aa41-2d71-4957-a779-fc11921c8373.png">

**Comment by MichaelDeBoey** [comment]
Tis is fixed now! 🥳🎉

**Comment by bouwe77** [comment]
Yes! 😃
