### ISSUE TITLE
Connect to Discord is broken

### ISSUE THREAD

**Issue by sreetamdas** [kentcdodds/kentcdodds.com#143]
Clicking on the "Connect to Discord" link on `/me` throws an error on the Discord page: `Invalid OAuth2 redirect_uri`.

Here's the link that was populated in the address bar: https://discord.com/oauth2/authorize?client_id=738096608440483870&redirect_uri=https%3A%2F%2Fkentcdodds.com%2Fdiscord%2Fcallback&response_type=code&scope=identify+guilds.join+email+guilds

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/11270438/135912155-3269b819-ebc5-4e0b-9156-1c7fc169a789.png)

</details>

**Comment by sreetamdas** [comment]
Update: refreshed and it seems to be fixed now, thanks!! Terrific job with the whole website 😄 👏

**Comment by MichaelDeBoey** [comment]
Tis is fixed now! 🥳🎉
