### ISSUE TITLE
"Edit on Github" and "Discuss on Twitter" hyperlinks point back to kentcdodds.com

### ISSUE THREAD

**Issue by rdylanwalker** [kentcdodds/kentcdodds.com#144]
I think this issue is self-explanatory, but the `Link`s in the `blog.$slug.tsx` point to root (`/`) instead of the correct external URL.

Relevant Code: https://github.com/kentcdodds/kentcdodds.com/blob/eae64606ead78112c109ba7d7a1e0333bca4f602/app/routes/blog.%24slug.tsx#L236-L250

I'm wondering if also the "Tweet this article" link and the "Discuss on Twitter" are redundant?  I'm not familiar with Twitter and it's nuances, so quite possibly they are not.

**Comment by kentcdodds** [comment]
This is fixed!
