### ISSUE TITLE
Blog Article Date Incorrect

### ISSUE THREAD

**Issue by rdylanwalker** [kentcdodds/kentcdodds.com#146]
Looks like `article.date` was mistyped (or mis-calculated) into the database for https://kentcdodds.com/blog/introducing-the-new-kentcdodds.com.  I'd like to believe I could time-travel though :)

![image](https://user-images.githubusercontent.com/4922876/135918502-4e48ee4f-3023-4081-a7d1-1c0823764625.png)
![image](https://user-images.githubusercontent.com/4922876/135918847-a90579d0-7e1e-42e1-a020-9892aa5ea2ad.png)

Code:
https://github.com/kentcdodds/kentcdodds.com/blob/808cc794e5ea0e8059b8c82d75c627c6defbe703/content/blog/introducing-the-new-kentcdodds.com.mdx#L3

I'd update it, but I'm not sure what it should be (or if the site was sent live early).

**Comment by kentcdodds** [comment]
Thanks! This was fixed 😅
