### ISSUE TITLE
Changing light/dark mode resets podcast player

### ISSUE THREAD

**Issue by twhitbeck** [kentcdodds/kentcdodds.com#151]
I was listening to one of the Chats with Kent episodes, and when I switched to dark mode the player reset to 0:00 and stopped.

**Comment by kentcdodds** [comment]
Yeah, that's a bummer. Unfortunately I can't know whether you're playing an episode and I want to display the right-mode iframe, so if you switch it loads a completely different iframe. I think this is one we just can't do anything about without building our own player which may happen one day, but not any time soon :(

**Comment by twhitbeck** [comment]
makes sense, thanks for taking the time to look into it and respond.
