### ISSUE TITLE
Inconsistent height of links in footer "YOU MIGHT ALSO LIKE"

### ISSUE THREAD

**Issue by Miklet** [kentcdodds/kentcdodds.com#160]
Hey Kent!

I was reading one of your great articles and I have found out that your links in footer have inconsistent height because of missing `height: 100%`.

Cheers

![image](https://user-images.githubusercontent.com/12592677/136343960-838fb589-0500-4907-88d7-3b59cc34a797.png)

**Comment by kentcdodds** [comment]
Thanks! I've opened a PR on that site to fix this :)

**Comment by Miklet** [comment]
> Thanks! I've opened a PR on that site to fix this :)

Oh right! This repository is not for that site 😂 My bad! Anyway, glad I could help.
