### ISSUE TITLE
kody-flying color variants

### ISSUE THREAD

**Issue by Aprillion** [kentcdodds/kentcdodds.com#162]
I was studying differences between kody-flying color variants:

<img width="1231" alt="Screenshot 2021-10-08 at 13 30 35" src="https://user-images.githubusercontent.com/1087670/136549553-3c9e0ade-8dcd-4a9d-beb3-85f27c34f280.png">

Most differences are probably artistic choice (yellow kody has cold-gray fur, red one is warm-gray; the light on red kody's right leg is white and not red, ...), but I noticed 1 minor difference that is probably not intentional and could be fixed:

* Light on the recycle icon ♻ on top of image is blue in all color variants, should be probably red/yellow/white in the non-blue versions.

**Comment by kentcdodds** [comment]
Unfortunately our illustrator ghosted us and getting other colors (other than blue) was manual work in photoshop 🤦‍♂️. Eventually we'll hopefully find someone who knows blender to give the Koala proper treatment...
