### ISSUE TITLE
read stats positioning

### ISSUE THREAD

**Issue by rbusquet** [kentcdodds/kentcdodds.com#164]
read stats grows over the "what's this" link, and sometimes the view count doesn't follow the theme

![Oct-08-2021 15-42-49](https://user-images.githubusercontent.com/7198302/136636345-3320be63-c1c5-4910-aece-874cdd8cd9ef.gif)

**Comment by smeijer** [comment]
The counter (18408) is also dark on dark there.

**Comment by kentcdodds** [comment]
Yeah, I'm not sure how that's possible...

**Comment by kentcdodds** [comment]
I think I fixed it :)
