### ISSUE TITLE
Unable to use submit function on Advanced React Patterns sign up form

### ISSUE THREAD

**Issue by danditomaso** [kentcdodds/kentcdodds.com#167]
I was getting an error signing up for the Advanced React Patterns workshop. While I was on this page (https://kentcdodds.com/workshops/advanced-react-patterns#sign-up) I had entered my  email and first name in the appropriate fields. After clicking "Sign Me Up" nothing happens, I checked the my dev tools console and saw I kept getting this error output for each time I had clicked the button. Using FF 92.0.1 on Mac OSX Big Sur

![image](https://user-images.githubusercontent.com/12192153/136674316-c4976cee-8f88-4f2f-9709-250e0adafed7.png)
![image](https://user-images.githubusercontent.com/12192153/136674322-01fa352e-58b6-4985-86ed-091f47fdce50.png)

**Comment by kentcdodds** [comment]
Thanks for the report! This broke due to an unexpected change in react-router beta. Pushing/deploying a fix now :)
