### ISSUE TITLE
Chats page shows error on Safari (desktop & mobile)

### ISSUE THREAD

**Issue by vedran** [kentcdodds/kentcdodds.com#171]
## Error

![image](https://user-images.githubusercontent.com/473826/136711193-46462c5b-a643-49f9-8909-b1ee4b3b69d3.png)

Context from twitter thread: https://twitter.com/vbudimcic/status/1447230664114270213

## Steps to reproduce:

1. Visit https://kentcdodds.com/chats/04 on Desktop Safari (Version 14.0.2 (16610.3.7.1.9)) or iOS Safari (iOS 14.4.2)

**Comment by kentcdodds** [comment]
When you open this does it have any code in it? https://polyfill.io/v3/polyfill.js?features=Intl%2CIntl.ListFormat%2CIntl.NumberFormat%2CIntl.RelativeTimeFormat

Could you tel me which features are in there?

**Comment by vedran** [comment]
There's a lot. I saved it in a gist: 
https://gist.github.com/vedran/2e320a9a70e5521d537142369610d1e7

**Comment by kentcdodds** [comment]
Great! Thank you! I've added that polyfill so it should work for you now
