### ISSUE TITLE
Homepage image doesn't show on Safari when devtools open

### ISSUE THREAD

**Issue by vedran** [kentcdodds/kentcdodds.com#172]
This one is strange. The big homepage image with the koala doesn't show up on Safari, but only when devtools are open.

![image](https://user-images.githubusercontent.com/473826/136711565-a8469b25-51df-4383-ab6c-95adb3823e71.png)

https://user-images.githubusercontent.com/473826/136711482-ca125444-98c9-496b-a394-7dcd2b806b56.mov

**Comment by adrianzielonka** [comment]
@vedran Can't seem to reproduce this issue in either Safari 14.1.2 or 15.0 on macOS Big Sur 11.6

Which macOS and Safari version are you running?

**Comment by vedran** [comment]
I can't repro it anymore either. I'll close this.
