### ISSUE TITLE
Call Kent Podcast page has missing episodes

### ISSUE THREAD

**Issue by matiadev** [kentcdodds/kentcdodds.com#178]
The [episode section on the calls page](https://kentcdodds.com/calls#episodes) is missing episodes. 

![Call Kent Podcast](https://user-images.githubusercontent.com/38083522/137145424-81fba976-2db7-4b78-aeb4-2e107aebff88.png)

**Comment by kentcdodds** [comment]
Thanks! Fixed in https://github.com/kentcdodds/kentcdodds.com/commit/a0c213cc1e3023e01d13d2cda29fdbc338bd27ed
