### ISSUE TITLE
Add sorting when trying to filter by topics

### ISSUE THREAD

**Issue by pavelkeyzik** [kentcdodds/kentcdodds.com#181]
What about to add sorting by date, when you're filtering blog posts by topics?

![image](https://user-images.githubusercontent.com/17102399/137300969-1f2942d1-41bf-4456-90cf-fc7ce878f176.png)

## Steps to reproduce:
1. Go to https://kentcdodds.com/blog
2. In the "Search blog by topics"section press on "state"

## Actual results:
Blog posts are sorted randomly. The first item with date September 23rd, 2019, but the second item is July 21st, 2020

## Expected result for me:
Blog posts are sorted by date descending. Newest posts at the very top

**Comment by kentcdodds** [comment]
This is tricky because we just put those categories into the search field and the sorting algorithm takes over so it's finding the articles that match best based on the search value. Not all posts match as strongly to your search.

**Comment by pavelkeyzik** [comment]
Oh... Got you 😅
