### ISSUE TITLE
Safari - menu button transformation issue

### ISSUE THREAD

**Issue by dawsonrichey** [kentcdodds/kentcdodds.com#190]
https://user-images.githubusercontent.com/20673325/137701339-059a55c2-e0a3-4f33-b3e7-36c38225c6d1.mov

**Comment by kentcdodds** [comment]
Oh yeah, this is a known issue 😅 it only happens when you resize the window so I decided to not look into it. Could be an easy fix though. I'll leave this issue open to remind me to look at it sometime. Thanks!

**Comment by smeijer** [comment]
yeah, it's really weird. Please don't resize your window :sweat_smile:

**Comment by clicktodev** [comment]
Tested this on both chrome and Firefox, same issue. I believe It's a bug in framer motion.
I narrowed it down to the variants prop on the menu svg in navbar.tsx.
```js
const topVariants = {
  open: {rotate: 45, y: 7},
  closed: {rotate: 0, y: 0},
}

const centerVariants = {
  open: {opacity: 0},
  closed: {opacity: 1},
}

const bottomVariants = {
  open: {rotate: -45, y: -5},
  closed: {rotate: 0, y: 0},
}

```

**Comment by clicktodev** [comment]
related to #43
