### ISSUE TITLE
maxAge value is in ms and not seconds

### ISSUE THREAD

**Issue by milamer** [kentcdodds/kentcdodds.com#198]
Hey Kent 👋 

I Just saw that you're using the [`linkExpirationTime` in maxAge](https://github.com/kentcdodds/kentcdodds.com/blob/d6eb0ad96010e991d6aacbc0b311e8d85237fe41/app/utils/login.server.ts), which is set to `1000 * 60 * 30`, but the maxAge should be in seconds: [see mdn](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie).
(The same with `sessionExpirationTime`)

So the timeout of the cookies is thousand times higher than intended.

**Comment by kentcdodds** [comment]
Nice catch! I'll get this fixed soon (if nobody beats me to it). Will probably just `/ 1000`

**Comment by kentcdodds** [comment]
Pushing fix now. Thanks!
