### ISSUE TITLE
Get a catch block error message with TypeScript: give a more "universal" solution

### ISSUE THREAD

**Issue by npirotte** [kentcdodds/kentcdodds.com#206]
Hi Kent, I went through your article about error handling, because we just faced the exact same issue :)

But we figured out that the proposed solution might not fit all cases, since many framework are throwing errors that comply to the Error api, but aren't instance of Error.

Then I would propose the following implementation as a more "universal" way of handling errors:

```ts
type ErrorWithMessage = {
  message: string;
}

function isErrorWithMessage(error: unknown): error is ErrorWithMessage {
  return typeof error === 'object' && 'message' in error;
}

function getErrorMessage(error: unknown) {
  if (isErrorWithMessage(error)) return error.message
  return String(error)
}
```

This should allow program to cope with any errors thrown by all frameworks (apollo, axios, etc…)

**Comment by kentcdodds** [comment]
Thanks! I've added this to the post :)

**Comment by jpeyper** [comment]
My typescript may not be the best, but the type guard doesn't guarantee that the message field on the error is a string, does it?

**Comment by kentcdodds** [comment]
Hi @jpeyper! You're right. I've updated the blog post to account for that. Thanks!
