### ISSUE TITLE
Long strings of unbroken text cause page overflow

### ISSUE THREAD

**Issue by jnahumphreys** [kentcdodds/kentcdodds.com#226]
**Expected behaviour:**
Long strings of unbroken text (e.g a url) should have necessary CSS rules to allow word breaking.

**Observed behaviour:**
A Twitter url within the blog article ["Write tests. Not too many. Mostly integration."](https://kentcdodds.com/blog/write-tests) is not able to wrap.On iPhone 13 portrait viewport, this is causing page overflow on the X axis. 

![image](https://user-images.githubusercontent.com/9253831/141696643-fe6db73c-e3fc-48d5-87e6-95644437af25.png)

**Suggested fix:**
Include required CSS rules to allow long unbroken strings to break / wrap

```css
overflow-wrap: break-word,
word-wrap: break-word,
word-break: break-word,
```

**Comment by kentcdodds** [comment]
Thanks! I'll look into this 👍

**Comment by amir-ziaei** [comment]
Face this on mobile today as well:

SS:
![image](https://user-images.githubusercontent.com/26747997/193472065-7f36a0b0-419e-4988-b255-00af8ca55935.png)

It causes a horizontal scroll which makes the UX unpleasant.

**Comment by kentcdodds** [comment]
Just pushed a fix to this 👍 Thanks!
