### ISSUE TITLE
Poor text contrast in dark mode on How to add testing to an existing project

### ISSUE THREAD

**Issue by dexter-stpierre** [kentcdodds/kentcdodds.com#233]
The testing trophy image has very poor contrast on dark mode due to the dark background. Could maybe use an alternate image, or use a background on that image in dark mode to make it possible to read

**Comment by kentcdodds** [comment]
Hi @dexter-stpierre,

Yeah, you're probably right. Which blog post do you see this on?

**Comment by dexter-stpierre** [comment]
Thanks for getting back to me, and thank you for all the awesome content you produce! It's this post: https://kentcdodds.com/blog/how-to-add-testing-to-an-existing-project

**Comment by kentcdodds** [comment]
Thanks! Fixed!
