### ISSUE TITLE
Failed to run locally

### ISSUE THREAD

**Issue by dpyzo0o** [kentcdodds/kentcdodds.com#234]
I followed the contribution guide to setup the project. Everything worked as expected as I ran `npm run setup`. However, when I run `npm run dev` and visit pages which have mdx content in it, the pages crashed. Here are the error messages:

<img width="874" alt="Screen Shot 2021-11-22 at 6 37 55 PM" src="https://user-images.githubusercontent.com/24768249/142846879-10763107-a201-4708-8fcd-1e6855e6e3f6.png">

It seems like something going wrong with mdx-bundler but I have no idea how to debug it.

Are there some setups that I'm missing?

**Comment by kentcdodds** [comment]
Huh! That's a funny one. Pushing a fix now. Thanks for letting me know!

**Comment by dpyzo0o** [comment]
@kentcdodds Unfortunately it does not fix the problem. I'm still facing the same error. There are also other parsing errors that I did not post before.

<img width="1234" alt="Screen Shot 2021-11-25 at 2 13 56 PM" src="https://user-images.githubusercontent.com/24768249/143389712-b23b1e05-0aa6-4753-ba56-db90de47fedf.png">
<img width="1224" alt="Screen Shot 2021-11-25 at 2 16 01 PM" src="https://user-images.githubusercontent.com/24768249/143389721-7f0e226b-22b3-419a-b5aa-84d192346ed1.png">
.
