### ISSUE TITLE
UX suggestion: list view for the blog posts

### ISSUE THREAD

**Issue by gabimor** [kentcdodds/kentcdodds.com#241]
I recently became a rather heavy user of your Kontent ;)
it's really great and I find my self taking "Kontent breaks", reading a blog post or listening to a call. 
One thing thats bothering a bit is that while everything looks really nice, I do find it hard to actually choose and get to what's interesting to me. Especially in the mobile blog where everything is huge and requires lots of scrolling, I find myself just wanting a list of titles to choose from.
Now I just find myself reading the MDX's in github.
It would be great to have a minimal list view for the blog post and endless scrolling

**Comment by kentcdodds** [comment]
You got it :)

https://kentcdodds.com/blog/list (deploying now: https://github.com/kentcdodds/kentcdodds.com/actions/runs/1519514213)

**Comment by nimrossum** [comment]
There seems to be an issue with this post that has a tweet: ![Screenshot_20211130-121228.jpg](https://user-images.githubusercontent.com/1959615/144037206-10c9100c-eb5e-42e1-b01e-3c5efef76a68.jpg)

**Comment by kentcdodds** [comment]
Deploying a fix now :) Thanks!
