### ISSUE TITLE
Navbar menu items stay selected when you go back to credits page

### ISSUE THREAD

**Issue by user9747** [kentcdodds/kentcdodds.com#269]
![image](https://user-images.githubusercontent.com/23278959/148697859-81d92d28-a9ef-49f5-b4b1-c29892ce33cb.png)

## Steps to reproduce:-
1. Open `/credits`
2. Click on navbar item `Chats`
3. Click browser back button

The navbar now shows that we are still on Chat page, but we have moved to `/credits`

**Comment by kentcdodds** [comment]
Hi @user9747,

I think what you're seeing is the focus is still on the chats link so it's highlighted. If you move focus (click anywhere else) the focus will move and it's no longer highlighted :)

Thanks anyway :)

**Comment by user9747** [comment]
Makes sense. So that means there would be a scenario were two nav items are focused at a time, if i haven't clicked anywhere after navigating.

**Comment by kentcdodds** [comment]
Right. Because we don't have a different style for the active page vs focus/hover states. That's by design. It probably could be better, but I don't think it's a significant issue.
