### ISSUE TITLE
Nested route in Chats keep pushing same path to browser history stack

### ISSUE THREAD

**Issue by user9747** [kentcdodds/kentcdodds.com#270]
## Steps to reproduce issue
1. Click `Chats` on navbar multiple times. (Each click pushes `/chats/04` to browser history stack (or whatever stack you have used internally))
2. Click browser back button (you will have to click the same number of times you clicked on `Chats` link)

**Comment by jasikpark** [comment]
I'm having an issue w/ the chat section as well:

https://kentcdodds.com/calls/01/56/using-graph-ql-queries-in-remix-loader-functions and other similar URLs give me a 501

**Comment by kentcdodds** [comment]
@jasikpark could you open a new issue? That's unrelated.

@user9747, that's happening because the `/chats` route is redirected to `/chats/{mostRecentSeason}`. It should probably just link straight to the most recent season. I need to fix that eventually.

**Comment by kentcdodds** [comment]
Nevermind @jasikpark, I fixed that too :)

Thanks for letting me know it was broken!

**Comment by jasikpark** [comment]
cool, nice!
