### ISSUE TITLE
How to study this project properly

### ISSUE THREAD

**Issue by mattchannn** [kentcdodds/kentcdodds.com#304]
Hi Kent,

I noticed a blog post talking about how this website is revamped, what technology it had been applied etc. I am just wondering 

- how could I study this project well because there're several topic I would like to study, redis, fly.io, docker, postgres ...
- such design must involve many architectural decision, may I know how you come up with this idea and could you give me some suggestion on how to enhance my skill on that
- pretty generic.. let say I look into material ui 's repo, how could I start studying such open source project

**Comment by kentcdodds** [comment]
Answering this live on https://kcd.im/office-hours :)

https://kentcdodds.com/blog/how-i-learn-an-open-source-codebase
https://kentcdodds.com/blog/how-i-built-a-modern-website-in-2021
