### ISSUE TITLE
Why do you need to refresh content?

### ISSUE THREAD

**Issue by jaschaio** [kentcdodds/kentcdodds.com#305]
Might be a stupid question, but couldn't you just use a redis key that's based on the hash of the content you are getting? If the content changes, the hash changes, and the cache breaks. Of course that would mean that the very first page load for a changed content might be slow, just as it is with any traditional server side caching (e.G. fastcgi cache) but it would remove the complexity of a github action for refreshing content. Or am I overlooking something?

**Comment by kentcdodds** [comment]
Hi @jaschaio,

Thanks for the idea. How would you get the hash? Where would you store the hash? How do you validate the hash?

**Comment by jaschaio** [comment]
Hey Kent,
sorry for the late reply, I thought I would eventually find time to build a prototype using github as a CRM and demonstrate what I mean, but from the looks of it I will have to use a headless CRM anyway so this won't apply to myself.

But to answer your questions:

> how would you get the hash?

Again, this might be naive but I think you have access to the file so you could just get the file contents and hash it, e.G.:

```js
import { readFile } from 'fs/promises';
import { createHash } from 'crypto';

const content = await readFile( './content/blog/automation.mdx' );

const hash = createHash( 'sha1' ).update( content ).digest( 'base64' );
```

Where the content is obviously the requested content

> Where would you store the hash? How do you validate the hash?

I don't think you would have to store or validate the hash. You just generate it from the current content's of the file. If the contents of the file change, the hash changes. And then you simply check if within redis there is some cached value for the hash, and if it isn't you would bundle it via `mdx-bundler` and cache it in redis for the next time it is requested.

**Comment by kentcdodds** [comment]
I'm concerned that creating the hash for the blog post and all relevant files would take longer than just reading the compiled code from the redis cache. And I think it would end up being more complicated than what I have.

Thanks though!
