### ISSUE TITLE
Polyfill.io net::ERR_CONNECTION_TIMED_OUT

### ISSUE THREAD

**Issue by SomiDivian** [kentcdodds/kentcdodds.com#314]
It took ~10s for the website to start,
~8s of that was trying to load polyfil.io and failed

console message
kentcdodds.com/:1          GET https://polyfill.io/v3/polyfill.min.js?features=Intl%2CIntl.ListFormat net::ERR_CONNECTION_TIMED_OUT

My connection speed 98 Mbps

**Comment by kentcdodds** [comment]
Thanks! I don't think I need it anyway.
