### ISSUE TITLE
Possibly incorrect depiction of strict mode

### ISSUE THREAD

**Issue by cheshireoctopus** [kentcdodds/kentcdodds.com#332]
👋 Hello!

Spotted a potential incorrect depiction of how strict mode works in [this post](https://kentcdodds.com/blog/react-strict-mode):

> Note that useEffect and useLayoutEffect callbacks are not called twice even in dev mode + strict mode because the entire point of those callbacks is to perform side-effects.

I have been operating with the understanding that `useEffect` is always called after the `render` method is invoked.

So, in the case of strict mode where `render` is called twice, wouldn't `useEffect` also be called twice (once for each render)?

Like with many things this might be my own personal misunderstanding. Apologies in advance if this turns out to be the case.

**Comment by kentcdodds** [comment]
Effects should only be called once a render has been committed, so once is correct.

That is until React 18 showed up and started calling your effect twice on mount in strict mode. Really poor decision IMO :(

Hope that helps explain things. If not, feel free to come to https://kcd.im/office-hours.
