### ISSUE TITLE
Twitter Embeds Image Broken

### ISSUE THREAD

**Issue by DhrumanGupta** [kentcdodds/kentcdodds.com#342]
The profile picture part of the custom Twitter embeds doesn't seem to be working, I've put an image of how they look to me (I tried both, on my PC and my phone). The image gives me a 404 when I try to open it (pbs.twimg)

![Screenshot_20220610_174534](https://user-images.githubusercontent.com/31363068/173062506-5c5ed432-924e-4d89-b35a-42777e7a6802.png)

**Comment by kentcdodds** [comment]
Thanks! Fixed.
