### ISSUE TITLE
move cachified to npm

### ISSUE THREAD

**Issue by Xiphe** [kentcdodds/kentcdodds.com#346]
Hey there 👋

I really like the [`cachified`](https://github.com/kentcdodds/kentcdodds.com/blob/main/app/utils/cache.server.ts) implementation and was wondering if anyone knows of an npm package with a similar api?

If not would it be ok if I took the code, made the remix implications optional and publish it to npm?

**Comment by kentcdodds** [comment]
The latest version of lru-cache seems to be able to support all the use cases. Care to try and see?

**Comment by Xiphe** [comment]
Which use cases do you mean? Would you rather remove the cachified abstraction and use lru-cache directly? Or do some parts of the implementation cater for cases that were not supported in previous lru-cache versions?

To be more precise I'd like to have a npm package with an API like this: 
https://github.com/kentcdodds/kentcdodds.com/blob/24ac1861bc28b8e9fe14483768a6e0603bd2cf6c/app/utils/blog.server.ts#L144-L151
and I don't see lru-cache providing anything in that direction (especially the ability to plug in redis instead of lru-cache)

**Comment by kentcdodds** [comment]
You're right. For some reason I thought it had a way to do that.

Would probably be cool to open source cachified. I've always wanted to. I just don't have the time to maintain another project. Anyone's welcome to take it and do that themselves. Hopefully they give credit where it's due :)

**Comment by Xiphe** [comment]
Cool! I'll give it a shot then! And rest assured I'll credit the work of you and your team.

**Comment by Xiphe** [comment]
First version is available as beta via `npm install cachified@0.0.1-beta.1` :octocat:  [Xiphe/cachified](https://github.com/Xiphe/cachified).
Ended up doing a buch of refinements. Will test it in rl add a few finishing touches + docs in the next days and then will try to integrate it back here.

@kentcdodds are you fine with me releasing this under MIT even though your source is GPL version 3?

**Comment by kentcdodds** [comment]
Yes, that's fine 👍 thanks!

**Comment by Xiphe** [comment]
Small update from my end, I consider the package stable now: https://github.com/Xiphe/cachified

I ended up finding and fixing a bunch of edge-cases and added some additional features. (most notably explicit stale-while-revalidate, supporting batch operations, and migrating values).

@kentcdodds would you still be interested in a PR switching from your implementation to the one I maintain?

**Comment by kentcdodds** [comment]
I welcome a PR, though I can't promise I'll accept it. For my own site there's a lot to be said for keeping code in-house. But I'd love to look at how using your package would change/improve things for me. Thanks!
