### ISSUE TITLE
Explain simply the difference between a testing framework, test runner and a testing library

### ISSUE THREAD

**Issue by jmherzo** [kentcdodds/kentcdodds.com#348]
So we always hear about Jest or RTL but I think there is always a confusion between what is a test runner, test library and a testing framework. It would be great to add it in this blog post just as a simple difference with examples.

**Comment by kentcdodds** [comment]
Hi @jmherzo! This is a great question. Have you read https://kentcdodds.com/blog/but-really-what-is-a-javascript-test yet? Give that a read and if you still have questions, feel free to ask me here: https://kcd.im/calls :)

**Comment by jmherzo** [comment]
I created this question from that blog actually 😂, as a way to improve one little sentence where you talk about it.

**Comment by kentcdodds** [comment]
Gotcha. I'd happily answer you on the Call Kent Podcast if you'd like to ask sometime :)
