### ISSUE TITLE
Error: Hydration failed because the initial UI does not match what was rendered on the server.

### ISSUE THREAD

**Issue by clicktodev** [kentcdodds/kentcdodds.com#352]
I noticed this error in the console log of the hosted build.
https://reactjs.org/docs/error-decoder.html/?invariant=418

**Comment by kentcdodds** [comment]
Ah, yeah, this probably has something to do with the fact that I started streaming and I do some funny things prior to hydration which may cause these issues. Would need more detailed digging... https://github.com/kentcdodds/kentcdodds.com/blob/5fc80afdadd686480714478eea36cde131166e0e/app/entry.client.tsx#L10

**Comment by clicktodev** [comment]
I look forward to the fix and I'm gonna use this chance to thank you for your hard work on all these technologies. Truly an inspiration 🚀
