### ISSUE TITLE
A link broken when opened in a new tab

### ISSUE THREAD

**Issue by amir-ziaei** [kentcdodds/kentcdodds.com#354]
I was reading [this article ](https://kentcdodds.com/blog/aha-testing) and I found a link that behaves strangely.

Under the **Nesting** section, there is a link to [Avoid Nesting in Tests](https://kentcdodds.com/blog/avoid-nesting-in-tests):
![image](https://user-images.githubusercontent.com/26747997/181222095-7d515739-2cc2-490d-9e01-945ba440b19e.png)

Left-clicking on this link works as any other internal link, however, the following operations result in me getting a JSON response:

- Open Link in New Tab
- Open Link in New Window
- Open Link in New Private Window

How it looks:
![image](https://user-images.githubusercontent.com/26747997/181222559-09ad73ca-039a-4b79-85ab-05a791f483c0.png)

Test environment:
- Windows 10
- Firefox Developer Edition v.104.0b2 (64-bit)
- Chrome v.103.0.5060.134 (Official Build) (64-bit)
- Microsoft Edge v.103.0.1264.71 (Official build) (64-bit)

**Comment by kentcdodds** [comment]
Thanks for finding this and letting me know!
