### ISSUE TITLE
Firefox - blurred image preview not swapping to full image

### ISSUE THREAD

**Issue by tywayne** [kentcdodds/kentcdodds.com#357]
When loading a page that has a blurred image preview, the image occasionally loads, replaces to the full image as expected, but then swaps back to the blurred image. 

Noticed on the blog index and detail screens, but may be happening elsewhere.
Seeing this only on FF from what I can tell. Works fine in Chrome/Safari.

## Steps to reproduce:
1. Load [this URL](https://kentcdodds.com/blog/get-a-catch-block-error-message-with-typescript) in Firefox
2. See blurred image preview
3. See the swap to full image
4. See the swap back to the blurred image preview

**Comment by kentcdodds** [comment]
I was able to reproduce this. Here's the code for that: https://github.com/kentcdodds/kentcdodds.com/blob/main/app/components/blurrable-image.tsx I'm guessing that somehow this variable somehow gets set to `false` again: https://github.com/kentcdodds/kentcdodds.com/blob/904683a165853ce3e5b87d95990f305e58f62a9d/app/components/blurrable-image.tsx#L14

I'm not sure...

**Comment by tywayne** [comment]
Fixed with [this commit](https://github.com/kentcdodds/kentcdodds.com/commit/54d11cefd15ece5a3ff0f1ab7233dfe2422fead8)
