### ISSUE TITLE
Add Service Worker with Workbox for UX

### ISSUE THREAD

**Issue by jdnichollsc** [kentcdodds/kentcdodds.com#363]
Hello mate, hope you're doing well

Is there any example using Service Workers for RemixJS? It would be great if we can provide the option to install the webapp as PWA for our customers.

Please let me know! <3

**Comment by kentcdodds** [comment]
Hi @jdnichollsc, I don't do Remix support in my website's issues. If you need support, please see https://remix.run/docs/en/v1/pages/community
