### ISSUE TITLE
bug: podcast player does't handle media playing/pausing

### ISSUE THREAD

**Issue by JLarky** [kentcdodds/kentcdodds.com#377]
If I open https://kentcdodds.com/calls/01/104/how-to-do-feature-flags-with-remix and I'm listening to an episode it only synchronizes state from play/pause button to audio tag, but doesn't do that the other way around. So if I play or pause by pressing F8 on mac or with a button on headphones, etc. it will cause media to play/pause but the state is not going to be reflected in the UI.

reproduction: https://www.youtube.com/watch?v=fUgk8Wi5jak

**Comment by kentcdodds** [comment]
Unfortunately that's an embedded player so we'll need to open a support ticket in transistor for this.

**Comment by kentcdodds** [comment]
Hopefully fixed https://twitter.com/TransistorFM/status/1580578060335599617?t=lnOBjg7qRSnl6eI1eTblAw&s=19
