### ISSUE TITLE
Blog on your Website is down

### ISSUE THREAD

**Issue by KainosShamusHarkin** [kentcdodds/kentcdodds.com#384]
I searched on google for an article I knew you wrote and it came up as first result.  I clicked on it and it directed me to your blog but I got 500 - Oh no, something did not go well.
"/blog/testing-implementation-details" is currently not working. So sorry.

You may know about it and It may be down for maintenance or whatever, im just letting you know incase it isn't.
Kind Regards

**Comment by kentcdodds** [comment]
My host had issues. It's working now.
