### ISSUE TITLE
Black friday notification message

### ISSUE THREAD

**Issue by ealch** [kentcdodds/kentcdodds.com#390]
There is an issue with the black friday notification with the unlogged users since as an unlogged user you don't have a team assigned and the `--color-team-unknown` is `white` for those users.

<img width="1568" alt="Screenshot 2022-11-25 at 13 06 15" src="https://user-images.githubusercontent.com/7937529/203983844-44bd6be0-d043-46e5-8648-58c5758f648c.png">

**Comment by kentcdodds** [comment]
Thanks! Fixed :)
