### ISSUE TITLE
https://kentcdodds.com/blog/using-fetch-with-type-script

### ISSUE THREAD

**Issue by nbouvrette** [kentcdodds/kentcdodds.com#395]
Not sure if this is the right place, but I stumbled on your blog post and saw something which I thought might be missing there. 

In the conclusion, you do an `const response = await window.fetch...` which is fine but, but shouldn't you also add a `.catch(error => error)` since `fetch` can throw errors?

I think that a lot of people are handling these errors poorly so it might be a good idea to clarify that point.

**Comment by kentcdodds** [comment]
Thanks for the issue.

It depends. In this case I think whoever is calling that function should handle the errors themselves 🤷‍♂️
