### ISSUE TITLE
Demo buttons in blog post not working

### ISSUE THREAD

**Issue by zxt-tzx** [kentcdodds/kentcdodds.com#396]
The two buttons under the [dispatch function updates section](https://kentcdodds.com/blog/use-state-lazy-initialization-and-function-updates#dispatch-function-updates) are not working — no matter how many times I click, they remain at zero. 

- tested with a few browsers (Safari, Chrome), all had this issue
- cloned the repo but it works fine locally, unable to reproduce

**Comment by kentcdodds** [comment]
They seem to work for me. They're just styled funny so they don't look like buttons. I'll take a look at that.

**Comment by zxt-tzx** [comment]
Oh I just tested them again and they work now. Very weird.

I suspect it might be a load-time issue, i.e. when I tried these buttons while loading the site, the site took a really long time to complete loading. But when I tried it just now, it's loads very quickly. Not sure if it's my network issue or if there was some change on your end! 

 Closing this issue now. Apologies for the false alarm!
