### ISSUE TITLE
Two bad `img` srcs on "The State Initializer Pattern" post

### ISSUE THREAD

**Issue by TomerAberbach** [kentcdodds/kentcdodds.com#399]
https://kentcdodds.com/blog/the-state-initializer-pattern

Specifically these:
- https://res.cloudinary.com/kentcdodds-com/image/upload/f_auto,q_auto,dpr_2.0,w_1600/v1636121505/kentcdodds.com/content/blog/the-state-initializer-pattern/key-reset.gif
- https://res.cloudinary.com/kentcdodds-com/image/upload/f_auto,q_auto,dpr_2.0,w_1600/v1636121497/kentcdodds.com/content/blog/the-state-initializer-pattern/state-initializer-pattern.gif

They seem to respond with 400

**Comment by TomerAberbach** [comment]
Well that was mighty quick, thanks!

**Comment by kentcdodds** [comment]
Thank you for taking the time to report this!
