### ISSUE TITLE
Improvement suggestion: add the rss discovery link

### ISSUE THREAD

**Issue by stof** [kentcdodds/kentcdodds.com#405]
Having a `<link>` tag in the head providing the URL of the feed would allow discovering the feed through a standard way (for instance, I have a Firefox extension that exposes such feeds in the browser UI)

**Comment by kentcdodds** [comment]
Sure! How do I do that? What does the `<link>` need to look like?

**Comment by stof** [comment]
`<link rel="alternate" type="application/rss+xml" title="..." href="..." />`, filling the title (with the title of the RSS feed) and `href` (with the URL of the feed) attributes.

**Comment by kentcdodds** [comment]
Cool, thanks for the help :)
