### ISSUE TITLE
404 error page doesn't show video/gif on safari browser

### ISSUE THREAD

**Issue by vonkoff** [kentcdodds/kentcdodds.com#407]
Both on IOS and Mac. My remix website has the same issue. Trying to see how to fix. 

### Steps to reproduce:

1. Load [a URL that doesn't exist](https://kentcdodds.com/error) in Safari. Both iPhone and on Mac. 
2. See video doesn't load in as it would on other browsers.

**Comment by kentcdodds** [comment]
Going to flag cloudinary for this one.

The URL is: https://res.cloudinary.com/kentcdodds-com/video/upload/f_auto,q_auto,c_fill,ac_none,ar_3:4,w_1000,fl_keep_dar/kentcdodds.com/misc/where_am_i

But Cloudinary selects `image/jp2` as the format for that for some reason...

If I add a `.mp4` at the end, Safari loads it just fine: https://res.cloudinary.com/kentcdodds-com/video/upload/f_auto,q_auto,c_fill,ac_none,ar_3:4,w_1000,fl_keep_dar/kentcdodds.com/misc/where_am_i.mp4

**Comment by kentcdodds** [comment]
Actually, even more interesting is that if I open the cloudinary URL directly in a Chromium-based browser it doesn't send a content-type at all and it shows a still frame 🙃

**Comment by colbyfayock** [comment]
got an answer about this

it looks like when you don't include the format (`.mp4`) and include `f_auto`, the CDN doesn't have enough information to go on I guess and determines to return the image

what you can do is apply `f_auto:video` to this (though currently undocumented) which will specify that you want to still use `f_auto`, but use a video format

**Comment by kentcdodds** [comment]
Very interesting considering it includes the `/video/` bit in the URL. But I'll do that. Thanks!

**Comment by colbyfayock** [comment]
for the curious, looks like the reason we can't use `/video` to determine is because audio files additionally use `/video` in the URL due to how it works technically
