### ISSUE TITLE
404 Error pages have non-functioning video on Safari IOS/Mac

### ISSUE THREAD

**Issue by vonkoff** [kentcdodds/kentcdodds.com#410]
Chiming in again to say that while the Error pages do now show the videos called "Where am I" on the 404 error pages they aren't in motion. 

As well, when on a Mac you are able to click to start playing the video. But, on iphone you cannot. Images below to show you what I mean. 

![IMG_E80212A304BF-1](https://user-images.githubusercontent.com/16548992/214282046-9c05d94f-6606-415b-84ea-ddb8e851b4e9.jpeg)

<img width="1035" alt="Screenshot 2023-01-24 at 12 39 17 PM" src="https://user-images.githubusercontent.com/16548992/214282320-dfeccb84-ef79-4f56-a46b-9b42b201122a.png">

**Comment by kentcdodds** [comment]
I'm afraid I don't know what to more to do about this. I tried it on my mac and it works fine. I don't have an iPhone so I can't test that. Unfortunately there's only so much time I can dedicate to this :(

**Comment by vonkoff** [comment]
It actually works on mac! Idk why it was different before, or maybe I was just hallucinating. 

Doesn't work on my iphone, but hey the image comes up. I think the message comes across either way.
