### ISSUE TITLE
Remote workshop message component shows NaN on countdown

### ISSUE THREAD

**Issue by sergiodxa** [kentcdodds/kentcdodds.com#420]
When you go to the website the message has all NaN for the countdown.

I tried it on Safari, Brave and Firefox and it only worked correctly in Brave (Chromium)

<img width="506" alt="Screenshot 2023-02-18 at 00 33 01" src="https://user-images.githubusercontent.com/1312018/219843041-5e53ce7d-452d-485e-84db-0772cfe62977.png">

**Comment by kentcdodds** [comment]
Thanks! Deploying a fix now.
