### ISSUE TITLE
Compilation error for blogs  [Build failed]

### ISSUE THREAD

**Issue by girishsavlesha** [kentcdodds/kentcdodds.com#459]
I followed the steps mentioned in `CONTRIBUTING.md` when I run `npm run prime-cache:mocks` I see bunch of similar errors for multiple blog markdown files. 

I tried to research on this not sure if this is related issue here https://github.com/shikijs/twoslash/issues/147

![image](https://github.com/kentcdodds/kentcdodds.com/assets/29174602/09bb0802-671f-4d0b-a42f-c8ea821a5917)

**Comment by kentcdodds** [comment]
Thanks for bringing this to my attention! All the blog posts on the website only work because they've been cached since we shipped this bug 😅 I don't know how long it would've taken me to notice something was wrong if you hadn't said something!

**Comment by kentcdodds** [comment]
Honestly, I should probably report to sentry when there's an error updating a value in the cache 😅
